drop view IF EXISTS view_weighted_average_capacity;
CREATE VIEW view_weighted_average_capacity AS
SELECT "PHYSICAL_CAPACITY" ,
	"AVAILABLE_CAPACITY",
	"WEIGHTED_PHYSICAL_SUBS_PERC" / "PHYSICAL_CAPACITY" AS "PHYSICAL_SUBS_PERC",
	"WEIGHTED_LOGICAL_USED_PERC" / "PHYSICAL_CAPACITY" AS "LOGICAL_USED_PERC",
	"WEIGHTED_PHYSICAL_USED_PERC" / "PHYSICAL_CAPACITY" AS "PHYSICAL_USED_PERC",
	"WEIGHTED_COMPRESSION_RATIO" / "PHYSICAL_CAPACITY" AS "COMPRESSION_RATIO",
	"WEIGHTED_CHANGE_DAY" / "PHYSICAL_CAPACITY" AS "CHANGE_DAY",
	"WEIGHTED_CHANGE_WEEK" / "PHYSICAL_CAPACITY" AS "CHANGE_WEEK",
	"WEIGHTED_CHANGE_MONTH" / "PHYSICAL_CAPACITY" AS "CHANGE_MONTH",
	"PHYSICAL_USED" AS "PHYSICAL_USED",
	"PHYSICAL_FREE" AS "PHYSICAL_FREE",
	"LOGICAL_CAPACITY" AS "LOGICAL_CAPACITY",
	"LOGICAL_USED" AS "LOGICAL_USED",
	"LOGICAL_FREE" AS "LOGICAL_FREE",
	"NET_TOTAL" AS "NET_TOTAL",
	"NET_USED" AS "NET_USED",
	"PHY_USED_BEF_SAVING" AS "PHY_USED_BEF_SAVING",
	"DEDUP_RATIO" AS "DEDUP_RATIO",
	"WEIGHTED_LOGICAL_SUBS_PERC" / "PHYSICAL_CAPACITY" AS "LOGICAL_SUBS_PERC",
	"WEIGHTED_NET_SUBS_PERC" / "PHYSICAL_CAPACITY" AS "NET_SUBS_PERC",
	"WEIGHTED_NET_USED_PERC" / "PHYSICAL_CAPACITY" AS "NET_USED_PERC"

FROM (
	SELECT
		SUM("PHYSICAL_CAPACITY") AS "PHYSICAL_CAPACITY",
		SUM("AVAILABLE_CAPACITY") AS "AVAILABLE_CAPACITY",
		SUM("PHYSICAL_SUBS_PERC" * "PHYSICAL_CAPACITY") AS "WEIGHTED_PHYSICAL_SUBS_PERC",
		SUM("LOGICAL_USED_PERC" * "PHYSICAL_CAPACITY") AS "WEIGHTED_LOGICAL_USED_PERC",
		SUM("PHYSICAL_USED_PERC" * "PHYSICAL_CAPACITY") AS "WEIGHTED_PHYSICAL_USED_PERC",
		SUM("COMPRESSION_RATIO" * "PHYSICAL_CAPACITY") AS "WEIGHTED_COMPRESSION_RATIO",
		SUM("CHANGE_DAY" * "PHYSICAL_CAPACITY") AS "WEIGHTED_CHANGE_DAY",
		SUM("CHANGE_WEEK" * "PHYSICAL_CAPACITY") AS "WEIGHTED_CHANGE_WEEK",
		SUM("CHANGE_MONTH" * "PHYSICAL_CAPACITY") AS "WEIGHTED_CHANGE_MONTH",
		SUM("PHYSICAL_USED") AS "PHYSICAL_USED",
		SUM("PHYSICAL_FREE") AS "PHYSICAL_FREE",
		SUM("LOGICAL_CAPACITY") AS "LOGICAL_CAPACITY",
		SUM("LOGICAL_USED") AS "LOGICAL_USED",
		SUM("LOGICAL_FREE") AS "LOGICAL_FREE",
		SUM("NET_TOTAL") AS "NET_TOTAL",
		SUM("NET_USED") AS "NET_USED",
		SUM("NET_FREE") AS "NET_FREE",
		SUM("PHY_USED_BEF_SAVING") AS "PHY_USED_BEF_SAVING",
		SUM("DEDUP_RATIO") AS "DEDUP_RATIO",
		SUM("LOGICAL_SUBS_PERC" * "PHYSICAL_CAPACITY") AS "WEIGHTED_LOGICAL_SUBS_PERC",
		SUM("NET_SUBS_PERC" * "PHYSICAL_CAPACITY") AS "WEIGHTED_NET_SUBS_PERC",
		SUM("NET_USED_PERC" * "PHYSICAL_CAPACITY") AS "WEIGHTED_NET_USED_PERC"
	FROM (
		SELECT * FROM crosstab(
			'SELECT id_pool,
				id_cat_metric_type,
				value
			 FROM view_pool_metrics
			 WHERE id_cat_metric_type IN (1, 2, 3, 4, 5, 6, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 38, 39, 40)
			 ORDER BY id_pool, id_cat_metric_type',
			 'SELECT DISTINCT id_cat_metric_type
			 FROM cat_metric_type
			 WHERE id_cat_metric_type IN (1, 2, 3, 4, 5, 6, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 38, 39, 40)
			 ORDER BY 1')
		AS ct(
			id_pool NUMERIC,
			"PHYSICAL_CAPACITY" NUMERIC,
			"PHYSICAL_SUBS_PERC" NUMERIC,
			"AVAILABLE_CAPACITY" NUMERIC,
			"LOGICAL_USED_PERC" NUMERIC,
			"PHYSICAL_USED_PERC" NUMERIC,
			"COMPRESSION_RATIO" NUMERIC,
			"CHANGE_DAY" NUMERIC,
			"CHANGE_WEEK" NUMERIC,
			"CHANGE_MONTH" NUMERIC,
			"PHYSICAL_USED" NUMERIC,
			"PHYSICAL_FREE" NUMERIC,
			"LOGICAL_CAPACITY" NUMERIC,
			"LOGICAL_USED" NUMERIC,
			"LOGICAL_FREE" NUMERIC,
			"NET_TOTAL" NUMERIC,
			"NET_USED" NUMERIC,
			"NET_FREE" NUMERIC,
			"PHY_USED_BEF_SAVING" NUMERIC,
			"DEDUP_RATIO" NUMERIC,
			"LOGICAL_SUBS_PERC" NUMERIC,
			"NET_SUBS_PERC" NUMERIC,
			"NET_USED_PERC" NUMERIC

		)
	) pivot
) totals;
